### ISSUE TITLE
Endpoints not working?

### ISSUE THREAD

**Issue by wernerb90** [gbandsmith/bitbucket-chat-bot#3]
Haai,

Default setup - added the credentials, the app is starting up.

The documentation says the endpoint is /bot/{room} - but that gives a 404.  On startup, the log shows: `Serving webhook endpoints for Google Hangout Platform at : http://0.0.0.0:3000/hangouts/receive` ... but that also gives a 404 from BitBucket.

![image](https://user-images.githubusercontent.com/6905546/52563165-4ba1f780-2e09-11e9-8c96-ebd2b0797ef3.png)

first one is /bot/{room} - 2nd one is /hangounts/receive/{room}

What is the correct endpoint?

I also get this on startup, does this thing need mongo?

```
(node:17721) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
(node:17721) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Running Node 8.9.0 on Ubuntu 16.04

**Comment by julbrs** [comment]
Hello

Yes it rely on Mongo. I will add it to doc !

Can you try again with a mongo db setup ? You can provide a ``MONGO_URL`` env variable if you not use a local mongo db.

**Comment by julbrs** [comment]
I have updated the README (bbe38c2d358643a193686866f8c56bee566060e0).

**Comment by wernerb90** [comment]
@bobman38 thanks - using that endpoint and mongo now, it's receiving requests and returning "ok" on tests and/or from bitbucket.

How do I troubleshoot the setup of the google account and/or room ID or is there anything else to do?

I keep getting `<h1>Not Found</h1>\n<h2>Error 404</h2>` as the error in the log, yet it returns "ok".

**Comment by julbrs** [comment]
Hello

Can you speak to the bot via hangout ? Do you have configured a new bot in Hangout using this guide ?
https://developers.google.com/hangouts/chat/how-tos/bots-publish

Thanks !

**Comment by wernerb90** [comment]
Haai @bobman38 -

Yes I can - the login doesn't seem to work as the client_id is missing?

![image](https://user-images.githubusercontent.com/6905546/52615975-b00f9600-2e9f-11e9-8541-2c6c8c77625a.png)

And the pull request webhook still gives 404 in the log ... whats missing?

**Comment by julbrs** [comment]
OK missing some configuration...

I will update the README today and will share this with you !

**Comment by wernerb90** [comment]
@bobman38 would be great - thanks

**Comment by wernerb90** [comment]
PS. I think `CREDS` in the documentation is also wrong, as I needed the google configuration json as `GOOGLE_APPLICATION_CREDENTIALS_DATA` ...

**Comment by julbrs** [comment]
OK big update of the README file. Must be better now !

https://github.com/gbandsmith/bitbucket-chat-bot#requirements this part show the google app configuration, and the bitbucket oauth consumer configuration.

https://github.com/gbandsmith/bitbucket-chat-bot#running-bitbucket-chat-bot-locally this part show how to run the tool locally, with the ``.env`` file.

I have also speak of the dokku deploy, where I use ``CREDS`` env variable (but right not in local mode !)

**Comment by wernerb90** [comment]
Hi @bobman38 - all great updates, thanks.

The BB part now partly works - I can login, but I can't connect a repository?

![image](https://user-images.githubusercontent.com/6905546/52664276-4a5bf200-2f11-11e9-829e-3093fd1561a1.png)

Also, the pull request webhook still gives the same "404 Not Found" error, so there's still a problem somewhere.... how do I diagnose that?

**Comment by julbrs** [comment]
Do you have logs in the console ?

**Comment by wernerb90** [comment]
@bobman38 

Yes - this:

```
debug: Error while sending message to Google Hangouts { Error: <h1>Not Found</h1>
<h2>Error 404</h2>

    at createError (/root/bitbucket-chat-bot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/bitbucket-chat-bot/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/root/bitbucket-chat-bot/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: 2147483648,
     validateStatus: [Function],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'Accept-Encoding': 'gzip',
        'User-Agent': 'google-api-nodejs-client/0.3.0 (gzip)',
        Authorization: 'Bearer X',
        'Content-Length': 662 },
     method: 'post',
     url: 'https://chat.googleapis.com/v1/AVAAxF52Of4/messages',
     paramsSerializer: [Function],
     data: 'valid json',
     params:
      { threadKey: 'https://bitbucket.org/xxx/yyy/pull-requests/44' } },
  request:
   ClientRequest {
     domain: null,
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'chat.googleapis.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 1167,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 48085,
        [Symbol(bytesRead)]: 846 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'chat.googleapis.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 1167,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 48085,
        [Symbol(bytesRead)]: 846 },
     _header: 'POST /v1/AVAAxF52Of4/messages?threadKey=https%3A%2F%2Fbitbucket.org%2Fxxx%2Fyyy%2Fpull-requests%2F44 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nAccept-Encoding: gzip\r\nUser-Agent: google-api-nodejs-client/0.3.0 (gzip)\r\nAuthorization: Bearer X\r\nContent-Length: 662\r\nHost: chat.googleapis.com\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/v1/AVAAxF52Of4/messages?threadKey=https%3A%2F%2Fbitbucket.org%2Fxxx%2Fyyy%2Fpull-requests%2F44',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 404,
        statusMessage: 'Not Found',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://chat.googleapis.com/v1/AVAAxF52Of4/messages?threadKey=https%3A%2F%2Fbitbucket.org%2Fxxx%2Fyyy%2Fpull-requests%2F44',
        redirects: [],
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 662,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://chat.googleapis.com/v1/AVAAxF52Of4/messages?threadKey=https%3A%2F%2Fbitbucket.org%2Fxxx%2Fyyy%2Fpull-requests%2F44' },
     [Symbol(outHeadersKey)]:
      { accept: [Array],
        'content-type': [Array],
        'accept-encoding': [Array],
        'user-agent': [Array],
        authorization: [Array],
        'content-length': [Array],
        host: [Array] } },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { 'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
        pragma: 'no-cache',
        expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
        date: 'Wed, 13 Feb 2019 04:06:37 GMT',
        server: 'ESF',
        'x-xss-protection': '1; mode=block',
        'x-frame-options': 'SAMEORIGIN',
        'x-content-type-options': 'nosniff',
        'alt-svc': 'quic=":443"; ma=2592000; v="44,43,39"',
        connection: 'close',
        'transfer-encoding': 'chunked' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: 2147483648,
        validateStatus: [Function],
        headers: [Object],
        method: 'post',
        url: 'https://chat.googleapis.com/v1/AVAAxF52Of4/messages',
        paramsSerializer: [Function],
        data: 'valid json',
        params: [Object] },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /v1/AVAAxF52Of4/messages?threadKey=https%3A%2F%2Fbitbucket.org%2Fxxx%2Fyyy%2Fpull-requests%2F44 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nAccept-Encoding: gzip\r\nUser-Agent: google-api-nodejs-client/0.3.0 (gzip)\r\nAuthorization: Bearer X\r\nContent-Length: 662\r\nHost: chat.googleapis.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/v1/AVAAxF52Of4/messages?threadKey=https%3A%2F%2Fbitbucket.org%2Fxxx%2Fyyy%2Fpull-requests%2F44',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: '<h1>Not Found</h1>\n<h2>Error 404</h2>\n' },
  code: '404' }
```

**Comment by wernerb90** [comment]
@bobman38 is that path correct to the API?

If I look at this issue - https://github.com/googleapis/google-api-nodejs-client/issues/1123

They have the endpoint as `/v1/spaces/{space}/messages?threadKey={threadKey}&key={auth}` ?  In this log I seem to be missing the `/spaces/` ?

**Comment by wernerb90** [comment]
Ok - it works now.  I had to update the webhook url to include "spaces/" before the ID of the room... probably worth putting that in the documentation as well, as well as where to get this ID for those that don't know - because it's not the room name...

**Comment by julbrs** [comment]
Exact. I have modified the README :+1: 

Do not hesitate to submit PR if you want ! 

So all is working for you now ? Can I close the case ?

THANKS,

**Comment by wernerb90** [comment]
All good - thanks so much!
